### ISSUE TITLE
Additional Official Plugins

### ISSUE THREAD

**Issue by antonywinn** [livehouse-automation/livehouse-docker-grafana#4]
vonage-status-panel
snuids-trafficlights-panel
grafana-clock-panel
grafana-piechart-panel

Might need more in future, but I think these ones have a definite use in "sample" dashboards to bundle on the brick.

**Comment by mikenye** [comment]
Dockerfile update, commit b119e33.

You won't be able to pull the docker image yet as I'll need to build it on arm platform.

I'll spin up an armv7l virtual machine tonight and build it.

**Comment by mikenye** [comment]
Done in commit 17cb17c90d27fa9a9f83d2e73a66b645bad728a6
